### ISSUE TITLE
Missing files and weights

### ISSUE THREAD

**Issue by ckhui** [callsys/ControlCap#1]
Hi there, I noticed that 'controlcap.common.evaluation.eval_densecap' is missing. 
Also, are there any plans to release the trained weights for the model?

Thank you for your attention to this matter, and for your great work on the project

**Comment by callsys** [comment]
The missing file has been uploaded. Trained weights are released in `https://github.com/callsys/ControlCap/blob/main/docs/data.md`.

**Comment by ckhui** [comment]
> The missing file has been uploaded. Trained weights are released in `https://github.com/callsys/ControlCap/blob/main/docs/data.md`.

Thank you
