### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by nicehuster** [callsys/ControlCap#3]
I tried training models with different configurations and found that they all couldn't converge. After 1k iterations, the loss values would basically become nan. What is the problem？
![17166061912336](https://github.com/callsys/ControlCap/assets/35832232/08fb861b-05e3-484c-a919-e01be2e5d74f)

**Comment by callsys** [comment]
What is the configuration of your server? It looks like you're using a small batch size. (We train the model with batch size 64 * 8 on 8 * A800 80G)

**Comment by nicehuster** [comment]
> What is the configuration of your server? It looks like you're using a small batch size. (We train the model with batch size 64 * 8 on 8 * A800 80G)

The models are trained using 8 NVIDIA A100 GPUs, and use the model's default configuration.

**Comment by callsys** [comment]
<img width="770" alt="截屏2024-05-25 11 36 40" src="https://github.com/callsys/ControlCap/assets/48741629/d9a93421-42e4-47d0-be2d-02b4855ac674">

<img width="866" alt="截屏2024-05-25 11 39 46" src="https://github.com/callsys/ControlCap/assets/48741629/297aeeb5-8a79-4d5e-b1c8-55082a818733">

I test with command `python -m torch.distributed.run --nproc_per_node=8 --master_port=29600 train.py --cfg-path configs/train/union/vg1.2_refcocog_5e.yaml`. It looks like your batch size is half of mine.

**Comment by nicehuster** [comment]
> <img alt="截屏2024-05-25 11 36 40" width="770" src="https://private-user-images.githubusercontent.com/48741629/333769461-d9a93421-42e4-47d0-be2d-02b4855ac674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDg5MTYsIm5iZiI6MTcxNjYwODYxNiwicGF0aCI6Ii80ODc0MTYyOS8zMzM3Njk0NjEtZDlhOTM0MjEtNDJlNC00N2QwLWJlMmQtMDJiNDg1NWFjNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAzNDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjBmOTZjZjIxNjdjNzIyNzJmYTc0MWFjYzAyOGZlNTA5N2IxMzgyOTEyYzUzMzI4NDkzNmM4OTE1OGNhODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ozux5qoyyxYphtzP9Lh3cTw_BTav1rIJ3o-HdgShkdU"> <img alt="截屏2024-05-25 11 39 46" width="866" src="https://private-user-images.githubusercontent.com/48741629/333769608-297aeeb5-8a79-4d5e-b1c8-55082a818733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDg5MTYsIm5iZiI6MTcxNjYwODYxNiwicGF0aCI6Ii80ODc0MTYyOS8zMzM3Njk2MDgtMjk3YWVlYjUtOGE3OS00ZDVlLWIxYzgtNTUwODJhODE4NzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAzNDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYmQxNWY1NDNiN2M0ZDA0MzY3NjEyNDBlZTc3MTllZjhiODdlOTdiY2MyYzlmZmY4YzBiNDUzODJiNTE5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._eZd5Khb51MD9Va78JxY1_AvdKN2m30LKUgHbwlmflw">
> I test with command `python -m torch.distributed.run --nproc_per_node=8 --master_port=29600 train.py --cfg-path configs/train/union/vg1.2_refcocog_5e.yaml`. It looks like your batch size is half of mine.

I use your command to retrain, the loss are also nan, 
![1716611458327](https://github.com/callsys/ControlCap/assets/35832232/6f36c759-90f7-4772-893e-7405c3794ef0)

**Comment by callsys** [comment]
Thanks for your feedback, we will test the code again. This afternoon we will open source another ControlCap-based work (Same environment with ControlCap), i.e., DynRefer, which contains all the ControlCap features and requires less memory for higher performance. You can wait for us to test the code again or turn to our new framework. We can remind you when the code is ready.

**Comment by nicehuster** [comment]
Ok, thanks, i look forward to your works!

**Comment by callsys** [comment]
We clean and rerun the code. The weight of the tagging loss is set to half of the orginal paper to make the training more stable. Here are the checkpoint and log file: [`ckpts/vg1.2_refcocog_5e.(pth/txt)`](https://mailsucasaccn-my.sharepoint.com/personal/zhaoyuzhong20_mails_ucas_ac_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fzhaoyuzhong20%5Fmails%5Fucas%5Fac%5Fcn%2FDocuments%2FControlCap&view=0). Besides, you  can also use our new framework [DynRefer](https://github.com/callsys/DynRefer), which contains all the ControlCap features and has better performance. Thanks!

**Comment by nicehuster** [comment]
> We clean and rerun the code. The weight of the tagging loss is set to half of the orginal paper to make the training more stable. Here are the checkpoint and log file: [`ckpts/vg1.2_refcocog_5e.(pth/txt)`](https://mailsucasaccn-my.sharepoint.com/personal/zhaoyuzhong20_mails_ucas_ac_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fzhaoyuzhong20%5Fmails%5Fucas%5Fac%5Fcn%2FDocuments%2FControlCap&view=0). Besides, you can also use our new framework [DynRefer](https://github.com/callsys/DynRefer), which contains all the ControlCap features and has better performance. Thanks!

ok, thanks.

**Comment by Xie-Shaofeng** [comment]
您好，我也遇到同样的loss为nan的问题，但是
<img width="292" height="37" alt="Image" src="https://github.com/user-attachments/assets/4afce3df-c76c-4aa5-8136-646a25c6e491" />这个日志文件我打不开，方便上传到网盘吗，麻烦您了，再次感谢

**Comment by callsys** [comment]
你好，我把log文件转到网盘了。链接: https://pan.baidu.com/s/1P3XqE65rMhQVl4T1EEr-PA 提取码: fs5a 
--来自百度网盘超级会员v7的分享

**Comment by Xie-Shaofeng** [comment]
感谢您！

> 你好，我把log文件转到网盘了。链接: https://pan.baidu.com/s/1P3XqE65rMhQVl4T1EEr-PA 提取码: fs5a --来自百度网盘超级会员v7的分享

**Comment by Xie-Shaofeng** [comment]
您好！因为我的资源受限，需要增大gradient_accumulate_steps来提高模型的稳定性。我在代码里没有找到gradient_accumulate_steps这一参数，可以在ControlCap\configs\base\runs\train.yaml中自己增加这一行吗？还是说需要在模型训练中自己定义？

<img width="1257" height="682" alt="Image" src="https://github.com/user-attachments/assets/6419cd91-8591-4059-af7e-7f709f9513cc" />

**Comment by callsys** [comment]
应该不能这么改，需要在controlcap/runners/runner.py line88 `train_stats = self.train_epoch(cur_epoch)`作出修改，让优化器每backward n个steps后更新一次。
